apiVersion: v2
name: trivy-ui
description: A web-based UI for visualizing and managing Trivy vulnerability scan results in Kubernetes clusters
type: application
version: 0.0.3
appVersion: "v0.0.3"
keywords:
  - trivy
  - security
  - vulnerability
  - kubernetes
  - dashboard
home: https://github.com/locustbaby/trivy-ui
sources:
  - https://github.com/locustbaby/trivy-ui
maintainers:
  - name: locustbaby
    email: locustbaby@example.com
